# Pandas - Einstieg

_pandas_ ist eine Programmbibliothek zur Verarbeitung und Analyse von Daten in der Programmiersprache Python. 
<br>
Insbesondere enthält sie Datenstrukturen und Operatoren für den Zugriff auf numerische und alphanumerische Tabellen und Zeitreihen, siehe 
[Pandas_(Software) - Wikipedia](https://de.wikipedia.org/wiki/Pandas_(Software))

Der Name _pandas_ wurde von  "**pan**el **da**ta" abgeleitet.

In diesem Notebook werden die beiden wichtigen Datenstrukturen von Pandas vorgestellt:
- Series - Vektor (ein-dimensional) mit Index (`pandas.core.series.Series`)
- DataFrame - Matrix / Tabelle mit Spaltenbezeichnungen und Zeilenbezeichungen (Index) (`pandas.core.frame.DataFrame`)

-----
2026-05-12 ug 1.10

<!--
Weiterer Datentyp:
Das erzeugte Objekt ist vom Typ: `pandas.core.indexes.base.Index`.
-->

---
### Vorbereitung
Python Packages laden

Das _pandas_ Paket wird mit `pd` abgekürzt.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.__version__

'3.0.1'

Ausgabe der Matplotlib-Plots im Notebook

In [3]:
%matplotlib inline

----
## Series - Objekt

Ein _Pandas Series-Objekt_ enthält ein eindimensionales Array aus Werten (Daten), wobei jeder Wert einen Bezeichner besitzen kann (Index), siehe [pandas-series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html).

**Beispiel:** Einer Reihe von Personen (angegeben durch Vornamen) wird jeweils ein Alter zugeordnet:  

    Person -> Alter in Jahren
    'Anton'    -> 28
    'Bernd'    -> 26
    'Claudia'  -> 30
    'Doris'    -> 25

zunächst Darstellung der Bezeichner (Personen) und der Werte (Alter) mit Python Listen:

In [4]:
meine_Bezeichner = ['Anton', 'Bernd', 'Claudia', 'Doris']
meine_Werte  = [28, 26, 30, 25]
meine_Bezeichner, meine_Werte

(['Anton', 'Bernd', 'Claudia', 'Doris'], [28, 26, 30, 25])

Mit dem Konstruktor `pd.Series()` wird ein _Pandas Series-Objekt_ erzeugt.

Wir geben zunächst nur die Werte unter dem Keyword Argument `data=` an:

In [5]:
pd.Series(data=meine_Werte)

0    28
1    26
2    30
3    25
dtype: int64

Die Ausgabe zeigt zwei Spalten an:
- In der zweiten Spalte stehen unsere Werte, das Alter der Personen.
- In der ersten Spalte wurde ein "Zählindex", welcher bei 0 beginnt, angelegt.

Jetzt erzeugen wir ein _Pandas Series-Objekt_, wo wir neben unseren Werten auch unsere Bezeichner angeben, hierzu verwenden wir das Keyword Argument `index=`:

In [6]:
pd.Series(data=meine_Werte,index=meine_Bezeichner)

Anton      28
Bernd      26
Claudia    30
Doris      25
dtype: int64

Unsere Bezeichner wurden als Index des Series-Objekt übernommen.

Wenn wir die Reihenfolge der Argumente einhalten, können wir die Namen der Argumente weglassen:

In [7]:
Alter = pd.Series(meine_Werte, meine_Bezeichner)
Alter

Anton      28
Bernd      26
Claudia    30
Doris      25
dtype: int64

#### Zugriff auf die Element in einem Pandas Series-Objekt

Wir können jetzt wie bei einem Python Dictionary auf die Daten unter Verwendung des Indexes als Schlüssel zugreifen:

In [8]:
Alter['Claudia']

np.int64(30)

Alternative können wir die Punkt-Notation verwenden.

In [ ]:
Alter.Claudia

Dies funktioniert nicht bei einem Python Dictionary.

In [9]:
d = {'Anton': 28, 'Bernd': 26, 'Claudia': 30, 'Doris': 25}
d['Claudia']

30

In [10]:
d.Claudia

AttributeError: 'dict' object has no attribute 'Claudia'

Verwendung der `.loc[]`- Methode; loc steht für Location.

In [11]:
Alter.loc['Claudia']

np.int64(30)

Runde Klammern `()` können nicht verwendet werden, es kommt zu einem **ValueError**: No axis named Claudia for object type Series

In [12]:
Alter.loc('Claudia')

ValueError: No axis named Claudia for object type Series

-----
#### Positionsindex (Integer)
Bei früheren Pandas Versionen konnte durch die Angabe eines Positionsindex (Integer) auf einen Wert zugegriffen werden:

Warnhinweis: Diese Möglichkeit wurde abgeschafft:
```
FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
```

In [13]:
Alter[2]

KeyError: 2

Für den Zugriff mit Positionsindex (Integer) ist das folgende Konstruckt `.iloc[]` zu verwenden, das wir aber noch ausführlicher behandeln werden.

In [14]:
Alter.iloc[2]

np.int64(30)

-----
#### Zugriff auf den Index
Zugriff auf den Index erfolgt über das Attribut `index`:

In [15]:
Alter.index

Index(['Anton', 'Bernd', 'Claudia', 'Doris'], dtype='str')

------
#### Datentyp des _Pandas Series-Objekts_

Der Datentyp des _Pandas Series-Objekts_ `Alter` ist `pandas.Series` (früher `pandas.core.series.Series`)

In [16]:
type(Alter)

pandas.Series

-----
### Alternative Möglichkeiten ein _Pandas Series-Objekt_ anzulegen

#### Numpy Arrays

Angabe der Daten als _**Numpy Array**_ und index als Liste

In [17]:
meine_Werte_Array = np.array(meine_Werte)
pd.Series(meine_Werte_Array, meine_Bezeichner)

Anton      28
Bernd      26
Claudia    30
Doris      25
dtype: int64

In [18]:
meine_Werte_Array = np.array(meine_Werte)
meine_Bezeichner_Array = np.array(meine_Bezeichner)
pd.Series(meine_Werte_Array, meine_Bezeichner_Array)

Anton      28
Bernd      26
Claudia    30
Doris      25
dtype: int64

In [19]:
meine_Bezeichner_Array

array(['Anton', 'Bernd', 'Claudia', 'Doris'], dtype='<U7')

In [20]:
meine_Bezeichner_Array[3] ="Reinhold"

In [21]:
meine_Bezeichner_Array

array(['Anton', 'Bernd', 'Claudia', 'Reinhol'], dtype='<U7')

Zeichenketten in der Länge begrenzt und bei Schreiben werden die Zeichen auf diese Länge reduziert.

Datentyp der Elemente in der Pandas Series

In [22]:
meine_Werte_Array.dtype

dtype('int64')

In [23]:
meine_Bezeichner_Array.dtype

dtype('<U7')

Bedeutung von dtype('<U7')
+ `U` steht für einen Unicode-String-Typ in NumPy.
+ `7` bedeutet, dass maximale Länge jedes Eintrags 7 Zeichen ist.
+ `<` ist nur die Byte-Order-Kennzeichnung (little-endian) und spielt bei Strings praktisch keine Rolle.

Kurz gesagt
`dtype('<U7')` bedeutet: ein NumPy-Array mit Unicode-Strings, maximal 7 Zeichen pro Element.

#### Python Dictionary
_**Python Dictionary**_, wobei die Dictionary-Schlüssel den Index bilden

In [24]:
mein_Dict = {'Anton'  :25, 
             'Bernd'  :26, 
             'Claudia':27, 
             'Doris'  :28 }
pd.Series(mein_Dict)

Anton      25
Bernd      26
Claudia    27
Doris      28
dtype: int64

Vorgabe Datentyp:

Eine explizite Vorgabe für den Datentyp der Werte durch den Parameter `dtype=`

In [25]:
mein_Dict = {'Anton'  :25, 
             'Bernd'  :26, 
             'Claudia':27, 
             'Doris'  :28 }
pd.Series(mein_Dict,dtype='uint32')

Anton      25
Bernd      26
Claudia    27
Doris      28
dtype: uint32

Ein Pandas Series Objekt kann beliebige Werte enthalten, auch Zeichenketten:

In [26]:
Personen = ['Anton', 'Bernd', 'Claudia', 'Doris']
Hobbies  = ['Kochen', 'Laufen', 'Radfahren', 'Lesen']
pd.Series(Hobbies, Personen)

Anton         Kochen
Bernd         Laufen
Claudia    Radfahren
Doris          Lesen
dtype: str

-----
### Unterschied Pandas Series und Python Dictionary?

Microsoft Copilot:
<br>
Der Unterschied zwischen Pandas Series und Python Dictionary ist mehr als nur die Syntax. Lassen Sie uns die beiden Strukturen genauer betrachten:

+ Syntax und zugehörige Methoden:

    + **Python Dictionary:**
    Ein Wörterbuch (Dictionary) ist eine grundlegende Datenstruktur in Python, die Schlüssel-Wert-Paare speichert. 
    Sie können auf Werte über ihre Schlüssel zugreifen, z. B. `x['key']`.
    + **Pandas Series:**
    Eine Pandas Series ist eine eindimensionale Datenstruktur, die mit Achsenbeschriftungen arbeitet. 
    Sie können Werte sowohl über ihre Schlüssel als auch über numerische Indizes abrufen, z. B `x.key` oder `x[0]` (Referenz 1).
+ Ordnung:
    + **Python Dictionary:** Standard-Python-Wörterbücher sind ungeordnete Mengen. Werte können nur über ihre Schlüssel abgerufen werden.
    + **Pandas Series:** Pandas Series sind geordnet, sodass Sie sowohl über Schlüssel als auch über numerische Indizes auf die Daten zugreifen können (Referenz 1).
+ Komplexität und Funktionalität:
    + **Python Dictionary:** Wörterbücher sind einfach und eignen sich gut, um einfache Schlüssel-Wert-Paare zu speichern.
    + **Pandas Series:** Pandas Series sind leistungsfähiger und bieten eine Vielzahl von Methoden und Attributen, die weit über die eines Python-Wörterbuchs hinausgehen. 
    Sie eignen sich gut für komplexe Datenmanipulationen, Zusammenführungen von Datensätzen und mehr (Referenz 2).

**Zusammenfassend:** 
+ Wenn Sie nur einfache Schlüssel-Wert-Paare speichern müssen, verwenden Sie das Standard-Wörterbuch. 
+ Wenn Sie jedoch komplexe Datenmanipulationen durchführen müssen, ist die Verwendung von Pandas Series empfehlenswert (Referenzen 1 und 2).

Referenzen:
1. [stackoverflow - difference between dictionary and pandas series in python](https://stackoverflow.com/questions/43635694/difference-between-dictionary-and-pandas-series-in-python)
2. [stackoverflow - when to use pandas series numpy ndarrays or simply python dictionaries](https://stackoverflow.com/questions/45285743/when-to-use-pandas-series-numpy-ndarrays-or-simply-python-dictionaries)

-----
### Verknüpfung von Series-Objekten

Addition von zwei _Series-Objekten_ mit identischen Index:

In [27]:
ser1 = pd.Series([ 1,  2,  3,  4],['A','B','C','D'])
ser2 = pd.Series([10, 20, 30, 40],['A','B','C','D'])
ser1+ser2

A    11
B    22
C    33
D    44
dtype: int64

die Reihenfolge der Elemente innerhalb der Indices muss nicht gleich sein; wir erzeugen ein _Series-Objekt_ mit umgekehrter Reihenfolge der Elemente des Index:

In [28]:
ser3 = pd.Series([40, 30, 20, 10],['D','C','B','A'])
ser3

D    40
C    30
B    20
A    10
dtype: int64

Bei der Addition der beiden _Series Objekten_ werden die Werte der entsprechenden Index-Elemente addiert:

In [29]:
ser1+ser3

A    11
B    22
C    33
D    44
dtype: int64

Addition von _Series-Objekten_ mit unterschiedlichen Indices:

-> fehlende Werte werden mit `NaN` - "Not a Number" dargestellt.

In [30]:
ser1 = pd.Series([ 1,  2,  3,  4],['A','B','C','D'])
ser2 = pd.Series([10, 20, 30, 50],['A','B','C',    'E'])
ser1+ser2

A    11.0
B    22.0
C    33.0
D     NaN
E     NaN
dtype: float64

-----
### Methoden von Serien-Objekten

#### Minimum und Maximum einer Serie bestimmen

- Wert, Index, Integer-Position

- Minimum [`.min()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.min.html),
[`.idxmin()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.idxmin.html),
[`.argmin()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.argmin.html)

- Maximum [`.max()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.max.html),
[`.idxmax()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.idxmax.html),
[`.argmax()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.argmax.html)

Wir erzeugen uns eine einfache Serie

In [31]:
meine_Bezeichner = ['z1', 'z2', 'z3', 'z4', 'z5']
meine_Werte      = [   4,    3,    5,    3,    8]
meine_Serie = pd.Series(data=meine_Werte,index=meine_Bezeichner)
meine_Serie

z1    4
z2    3
z3    5
z4    3
z5    8
dtype: int64

In der Serie `meine_Serie` ist 3 die kleinste Zahl. 
<br>
Diese kommt zweimal vor; einmal bei `z2` und noch bei `z4`.
<br>
<br>
Bestimmung des kleinsten Wertes in der Serie mit `.min()`:

In [32]:
meine_Serie.min()

np.int64(3)

Bestimmung des Index, wo der erste kleinste Wert vorkommt mit `.idxmin()`:

In [33]:
meine_Serie.idxmin()

'z2'

So erhalte ich den Wert über den Index:

In [ ]:
meine_Serie[meine_Serie.idxmin()]

oder mit der `.loc[]`-Methode

In [34]:
meine_Serie.loc[meine_Serie.idxmin()]

np.int64(3)

Bestimmung der Integer-Position, wo der erste kleinste Wert vorkommt mit `.argmin()`:

In [35]:
meine_Serie.argmin()

np.int64(1)

Mit der `.iloc`-Methode erhalte ich den Wert über die Index-Position:

In [ ]:
meine_Serie.iloc[meine_Serie.argmin()]

So erhalte ich den Index über die Integer-Position:

In [36]:
meine_Serie.index[meine_Serie.argmin()]

'z2'

Wie bekomme ich alle Indices, wo der kleinste Wert auftritt?

In [37]:
meine_Serie

z1    4
z2    3
z3    5
z4    3
z5    8
dtype: int64

Verwenden einer Maske
- Bestimmung des Minimalwertes
- erstellen einer Maske, die nach dem Minimalwert sucht
- Maske auf Serien-Objekt anwenden und Indices ausgeben

In [38]:
min_Wert_meine_Serie = meine_Serie.min()
mask = meine_Serie==min_Wert_meine_Serie
print(mask)
meine_Serie[mask].index

z1    False
z2     True
z3    False
z4     True
z5    False
dtype: bool

Index(['z2', 'z4'], dtype='str')

Das entsprechende für die Maximalenwerte

In [39]:
max_Wert_meine_Serie = meine_Serie.max()
print(max_Wert_meine_Serie)
mask = meine_Serie==max_Wert_meine_Serie
print(mask)
print(meine_Serie[mask])
meine_Serie[mask].index

8
z1    False
z2    False
z3    False
z4    False
z5     True
dtype: bool
z5    8
dtype: int64

Index(['z5'], dtype='str')

-----
## DataFrame - Objekt

Ein _Pandas DataFrame-Objekt_ kann man sich aus mehreren _Pandas Series-Objekten_ vorstellen, die sich einen gemeinsamen Index teilen, siehe [pandas-dataframe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html).

Ein _Pandas DataFrame-Objekt_ ist zwei-dimensional (Zeilen und Spalten).
Die Spalten können unterschiedliche Datentypen aufnehmen. Die Werte einer Spalten sind aber alle von einem Datentyp.

Neben den Daten (`data=`) und dem Index (`index=`) wird zusätzlich eine Liste mit den Bezeichner der _Pandas Series-Objekten_ angegeben (`columns=`).

Das Pandas DataFrame-Objekt kann als eine zwei-dimensionale Tabelle dargestellt werden mit:

- `data=` Werte in zwei dimensionaler Darstellung, z.B. als Liste von Listen
- `index=` Bezeichnung der Zeilen, z.B. als Liste
- `columns=` Bezeichnung der Spalten, z.B. als Liste

### Erzeugen eines _Pandas DataFrame-Objektes_ 

**Beispiel**: Tabelle mit 4 Zeilen und 3 Spalten und den Zahlen von 1 bis 12

In [40]:
my_index   = ['Zeile1','Zeile2','Zeile3','Zeile4']
my_columns = ['Spalte1','Spalte2','Spalte3']
my_data    = [[ 1, 2, 3],
              [ 4, 5, 6],
              [ 7, 8, 9],
              [10,11,12]]
df = pd.DataFrame(data=my_data,index=my_index,columns=my_columns)
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

Das _Pandas DataFrame-Objekt_ `df` ist vom Typ  `pandas.DataFrame` (früher `pandas.core.frame.DataFrame`)

In [41]:
type(df)

pandas.DataFrame

-----
### Metadaten über den _Pandas DataFrame_:

#### Anzahl der Zeilen und Spalten (`.shape`-Attribut)

Das [`.shape`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html)-Attribut liefert ein Tupel mit der Anzahl der Zeilen und der Spalten eines DataFrames.

-  `.shape[0]` -> Anzahl der Zeilen  (Index)
-  `.shape[1]` -> Anzahl der Spalten (Columns)

In [42]:
df.shape

(4, 3)

#### Datentypen der Spalten (`.dtypes`-Attribut)

Das [`.dtypes`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dtypes.html)-Attribut liefert die Datentypen der Spalten. Es wird als ein _Pandas Series-Objekt_ zurückgegeben.

In [43]:
df.dtypes

Spalte1    int64
Spalte2    int64
Spalte3    int64
dtype: object

Das was `.dtypes` zurückgibt ist ein _Pandas Series_-Objekt

In [44]:
type(df.dtypes)

pandas.Series

Die Datentypen werden durch dtype-Objekte angegeben.

In [45]:
df.dtypes['Spalte1']

dtype('int64')

#### Metadaten zu den Zeilen und Spalten (`.info()`-Methode)
Die [`.info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html)-Methode liefert Metadaten zu den Zeilen (Index) und den Spalten (Columns).

In [46]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Zeile1 to Zeile4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Spalte1  4 non-null      int64
 1   Spalte2  4 non-null      int64
 2   Spalte3  4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

#### Spaltenamen (`.columns`-Attribute)

Das [`.columns`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html)-Attribute liefert die Spaltennamen und deren Reihenfolge.

Das erzeugte Objekt ist vom Typ: `pandas.Index` (früher `pandas.core.indexes.base.Index`).

In [47]:
df.columns

Index(['Spalte1', 'Spalte2', 'Spalte3'], dtype='str')

In [48]:
type(df.columns)

pandas.Index

#### Zeilennamen (`.index`-Attribut)

Das [`.index`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.index.html)-Attribut liefert die Zeilennamen und deren Reihenfolge. 

Das erzeugte Objekt ist auch vom Typ: `pandas.Index` (früher `pandas.core.indexes.base.Index`).

In [49]:
df.index

Index(['Zeile1', 'Zeile2', 'Zeile3', 'Zeile4'], dtype='str')

In [50]:
type(df.index)

pandas.Index

------
### Zugriff auf die Spalten (Columns) des DataFrames

#### Zugriff auf eine Spalte
Zugriff auf eine Spalte durch Angabe des Names der Spalte in eckigen Klammern:

`df['Spaltenname']`

Es wird ein _Pandas Series_-Objekt zurückgegeben: `pandas.Series` (früher `pandas.core.series.Series`)

In [51]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

In [52]:
print(df)

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

In [53]:
df['Spalte2']

Zeile1     2
Zeile2     5
Zeile3     8
Zeile4    11
Name: Spalte2, dtype: int64

In [54]:
type(df['Spalte2'])

pandas.Series

Neben der Notation mit eckigen Klammern `[]` gibt es die _Punkt-Notation_ (dot-notation) um eine Spalte anzusprechen:
`df.Spalte2`:

In [55]:
df.Spalte2

Zeile1     2
Zeile2     5
Zeile3     8
Zeile4    11
Name: Spalte2, dtype: int64

_Anmerkung zur Punkt-Notation_: 
- Die Punkt-Notation funktioniert nur bei Spaltennamen, die keine Leerzeichen und keine Sonderzeichen enthalten.
- Auch dürfen sich die Spaltennamen nicht mit Attributen und Methoden des DataFrame überschneiden, z.B. `.index`, `.count()`

#### Zugriff auf mehrere Spalte gleichzeitig
Der Zugriff auf mehrere Spalten erfolgt durch Angabe einer Liste der Spaltennamen in eckigen Klammern:

`df[['Spaltenname1','Spaltenname2']]` 

Es wird ein _Pandas DataFrame_-Objekt zurückgegeben: `pandas.DataFrame` (früher `pandas.core.frame.DataFrame`)

In [56]:
df[['Spalte2','Spalte3']]

        Spalte2  Spalte3
Zeile1        2        3
Zeile2        5        6
Zeile3        8        9
Zeile4       11       12

In [57]:
type(df[['Spalte2','Spalte3']])

pandas.DataFrame

Man beachte:
+ `df['Spalte2']` gibt eine Pandas Serie zurück
+ `df[['Spalte2']]` gibt einen Pandas DataFrame zurück

In [58]:
type(df['Spalte2'])

pandas.Series

In [59]:
type(df[['Spalte2']])

pandas.DataFrame

In [60]:
df['Spalte2']

Zeile1     2
Zeile2     5
Zeile3     8
Zeile4    11
Name: Spalte2, dtype: int64

In [61]:
df[['Spalte2']]

        Spalte2
Zeile1        2
Zeile2        5
Zeile3        8
Zeile4       11

Frage: Wird unterschiedlich viel Speicher für eine Serie und ein DataFrame mit nur einer Spalte belegt?
<br>
Antwort: Nein, wird es nicht.

In [63]:
import sys

In [64]:
sys.getsizeof(df['Spalte2'])

456

In [65]:
sys.getsizeof(df[['Spalte2']])

456

------
#### Erstellen einer neuen Spalte

Ein neue Spalte kann durch Zuweisen der Kombination bestehender Spalten erstellt werden.

In [66]:
df['Spalte_neu'] = df['Spalte2'] + df['Spalte3']
df

        Spalte1  Spalte2  Spalte3  Spalte_neu
Zeile1        1        2        3           5
Zeile2        4        5        6          11
Zeile3        7        8        9          17
Zeile4       10       11       12          23

------
#### Entfernen einer Spalte

Spalten können mit der `.drop()`-Methode entfernt werden. [pandas-drop](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html)

`.drop('Spaltenname', axis=1)`

Hier muss angegeben werden, in welcher "Richtung" entfernt werden soll:
- axis=0 -> Zeilen (default-Einstellung) -> dies ist hier die falsche Richtung
- axis=1 -> Spalten -> dies brauchen wir hier

In [67]:
df2 = df.drop('Zeile2')
df2

        Spalte1  Spalte2  Spalte3  Spalte_neu
Zeile1        1        2        3           5
Zeile3        7        8        9          17
Zeile4       10       11       12          23

In [68]:
df2 = df.drop('Spalte_neu',axis=1)
df2

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

Es wird ein DataFrame zurückgegeben, in dem die Spalte 'Spalte_neu' entfernt wurde.
Der ursprüngliche DataFrame `df` wurde nicht verändert, hier ist die 'Spalte_neu' noch enthalten:

In [69]:
df

        Spalte1  Spalte2  Spalte3  Spalte_neu
Zeile1        1        2        3           5
Zeile2        4        5        6          11
Zeile3        7        8        9          17
Zeile4       10       11       12          23

Soll die Spalten 'Spalte_neu' im ursprüngliche DataFrame `df` entfernt werden, muss der Parameter `inplace=` auf `True` gesetzt werden.

In [70]:
df.drop('Spalte_neu',axis=1,inplace=True)
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

#### Entfernen einer Zeile

Durch `.drop('Zeilenname')` wird die Zeile mit dem Index 'Zeilename' entfernt.
Mit den Default-Einstellungen (`axis=0, inplace=False`) wird eine Kopie des veränderten DataFrame zurückgegeben und der ursprüngliche DataFrame bleibt unverändert.
<br>
Soll die Zeile im ursprünglich DataFrame entfernt werden, ist der Parameter `inplace=True` zu setzen.

In [71]:
df.drop('Zeile3')

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile4       10       11       12

In [72]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

Durch Übergabe einer Liste von Zeilennamen können mehrere Spalten oder Zeilen entfernt werden:

In [73]:
df.drop(['Zeile2','Zeile3'])

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile4       10       11       12

---
### Zugriff auf Zeilen (Index) des DataFrames

Für den Zugriff auf die Zeilen des DataFrames gibt es zwei Methoden:
- [`loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)-> (loc für **loc**ation) -> Verwendung der Zeilennamen 
- [`iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)-> (iloc für **i**nteger **loc**ation) -> Verwendung von Integer Positionen 

**Hinweis:** Man beachte die eckigen Klammern `[]` bei `loc[]` und bei `iloc[]`

Wir geben zur Erinnerung nochmal den Dataframe `df` aus, den wir im folgenden verwenden wollen:

In [74]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

#### Auswahl einer Zeile

Als Beispiel wollen wir die zweite Zeile auswählen. 

Die ausgewählte Zeile wird als _Series-Objekt_ `pandas.Series` zurückgegeben. 

Auswahl durch den Zeilennamen 'Zeile2' und `loc[]`:

In [75]:
df.loc['Zeile2']

Spalte1    4
Spalte2    5
Spalte3    6
Name: Zeile2, dtype: int64

In [76]:
type(df.loc['Zeile2'])

pandas.Series

Auswahl durch die Integer Position und `iloc[]`:

In [77]:
df.iloc[1]

Spalte1    4
Spalte2    5
Spalte3    6
Name: Zeile2, dtype: int64

#### Auswahl mehrer Zeilen

- als Liste von Zeilennamen oder Integer-Positionsangaben  -> doppelte eckige Klammern `[[Name1,Name2]]` oder  `[[IntegerPosition1,IntegerPosition2]]` (Anmerkung: `[Name1,Name2]` hat eine andere Bedeutung siehe unten)

In [78]:
df.loc[['Zeile2','Zeile3']]

        Spalte1  Spalte2  Spalte3
Zeile2        4        5        6
Zeile3        7        8        9

In [79]:
df.iloc[[1,2]]

        Spalte1  Spalte2  Spalte3
Zeile2        4        5        6
Zeile3        7        8        9

----
#### Bereich an Zeilen herauskopieren  mit "Slicing"-Operatoren

"Slicing"-Operatoren
- bei Verwendung von Zeilennamen `.loc[start-Name:stop-Name:step]` und 
- bei Verwendung von Integerpositionen `.iloc[start-Position:stop-Position:step]`

_**Achtung: Stop wird bei Zeilennamen und Integerpositionen unterschiedlich behandelt**_:
- bei `.loc` ist das Stop enthalten (inklusive)
- bei `.iloc` ist das Stop nicht enthalten (exklusive)

**Beispiel:** Ausgabe der zweiten und dritten Zeile unter Verwendung der Zeilennamen:

In [83]:
df.loc['Zeile2':'Zeile3']

        Spalte1  Spalte2  Spalte3
Zeile2        4        5        6
Zeile3        7        8        9

**Beispiel:** Ausgabe der zweiten und dritten Zeile unter Verwendung der Integerpositionen:

Hier müssen wir `df.iloc[1:3]` und nicht `df.iloc[1:2]` angeben.

In [86]:
df.iloc[1:3]

        Spalte1  Spalte2  Spalte3
Zeile2        4        5        6
Zeile3        7        8        9

---
### Auswahl eines Elements und eines Bereiches des DataFrames

Bei `.loc[]` und `.iloc[]` läst sich ein zweiter Parameter in den äußeren eckigen Klammern angeben, mit welchen Spalten ausgewählt werden können: `.loc[Zeilenauswahl,Spaltenauswahl]`. 

Bei `.loc[]` kann für die Zeilen- und Spaltenauswahl:
- ein Bezeichner
- eine Liste von Bezeichner ausgewählt werden
- eine Slicing-Operator eingesetzt werden

**Beispiel:** Auswahl eines Elements in Zeile _'Zeile2'_ und Spalte _'Spalte3'_:

In [87]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

In [88]:
df.loc['Zeile2','Spalte3']

np.int64(6)

**Beispiel:** Auswahl eines Bereichs in Zeile _'Zeile2'_ und Spalten _'Spalte2'_ und _'Spalte3'_:

In [89]:
df.loc['Zeile2',['Spalte2','Spalte3']]

Spalte2    5
Spalte3    6
Name: Zeile2, dtype: int64

**Beispiel:** Auswahl eines Bereichs in Zeilen _'Zeile2'_ und _'Zeile4'_ und Spalten _'Spalte2'_ und _'Spalte3'_:

In [90]:
df.loc[['Zeile2','Zeile4'],['Spalte2','Spalte3']]

        Spalte2  Spalte3
Zeile2        5        6
Zeile4       11       12

Die Reihenfolge in einer Auswahlliste kann beliebig gewählt werden, hierdurch kann ein Umsortieren durchgeführt werden.

In [91]:
df.loc[:,['Spalte3','Spalte1','Spalte2']]

        Spalte3  Spalte1  Spalte2
Zeile1        3        1        2
Zeile2        6        4        5
Zeile3        9        7        8
Zeile4       12       10       11

In [92]:
df[['Spalte3','Spalte1','Spalte2']]

        Spalte3  Spalte1  Spalte2
Zeile1        3        1        2
Zeile2        6        4        5
Zeile3        9        7        8
Zeile4       12       10       11

In [99]:
zeile_liste = [ zeile for zeile in df.index   if zeile not in ['Zeile2','Zeile4'] ] 
zeile_liste

['Zeile1', 'Zeile3']

In [100]:
df.loc[zeile_liste,['Spalte3','Spalte1','Spalte2']]

        Spalte3  Spalte1  Spalte2
Zeile1        3        1        2
Zeile3        9        7        8

-----
### Schreiben von Werten

In [93]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

Lesen eines Wertes

In [94]:
df.loc['Zeile2','Spalte3']

np.int64(6)

Schreiben eines Wertes

In [101]:
df.loc['Zeile2','Spalte3'] = 100

In [102]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5      100
Zeile3        7        8        9
Zeile4       10       11       12

In [103]:
df.iloc[1,2]

np.int64(100)

In [104]:
df.iloc[1,2] = 6

In [105]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

Lesen einer Zeile

In [106]:
df.loc['Zeile2']

Spalte1    4
Spalte2    5
Spalte3    6
Name: Zeile2, dtype: int64

Schreiben einer Zeile

In [107]:
df.loc['Zeile2'] = [11,12,13]

In [108]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2       11       12       13
Zeile3        7        8        9
Zeile4       10       11       12

auch **Broadcasting** ist möglich

In [109]:
df.loc['Zeile3']

Spalte1    7
Spalte2    8
Spalte3    9
Name: Zeile3, dtype: int64

In [110]:
df.loc['Zeile3'] = 5

In [111]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2       11       12       13
Zeile3        5        5        5
Zeile4       10       11       12

Lesen einer Spalte

In [112]:
df.loc[:,'Spalte2']

Zeile1     2
Zeile2    12
Zeile3     5
Zeile4    11
Name: Spalte2, dtype: int64

Schreiben einer Spalte

In [113]:
df.loc[:,'Spalte2'] = 6

In [114]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        6        3
Zeile2       11        6       13
Zeile3        5        6        5
Zeile4       10        6       12

Bereich lesen

In [115]:
df.loc['Zeile1':'Zeile3','Spalte2':'Spalte3']

        Spalte2  Spalte3
Zeile1        6        3
Zeile2        6       13
Zeile3        6        5

Bereich schreiben

In [116]:
df.loc['Zeile1':'Zeile3','Spalte2':'Spalte3'] = [[11,12],[21,22],[31,32]]

In [117]:
df

        Spalte1  Spalte2  Spalte3
Zeile1        1       11       12
Zeile2       11       21       22
Zeile3        5       31       32
Zeile4       10        6       12

---
### Auswahl mit Bedingungen

Wir erzeugen uns einen neuen DataFrame mit normalverteilten Zufallszahlen:
- 4 Spalten: 'A', 'B', 'C', 'D'
- 5 Zeilen: 'z1', 'z2', 'z3', 'z4', 'z5'

In [127]:
np.random.seed(17) # wir definieren den Startwert des Zufallsgenerators, um immer die gleichen Zufallszahlen zu bekommen
my_columns = ['A', 'B', 'C', 'D']
my_index = ['z1', 'z2', 'z3', 'z4', 'z5']
my_data = np.random.randn(len(my_index),len(my_columns))

df = pd.DataFrame(my_data,my_index,my_columns)
df

           A         B         C         D
z1  0.276266 -1.854628  0.623901  1.145311
z2  1.037190  1.886639 -0.111698 -0.362101
z3  0.148675 -0.437783  2.171257  1.152310
z4 -1.818812 -0.138049  0.539840 -1.775282
z5  1.314877 -0.473448 -1.092230 -0.250027

#### Herausfiltern von Elementen
Jetzt suchen wir positive Zahlen im gesamten DataFrame:

In [128]:
df>0

        A      B      C      D
z1   True  False   True   True
z2   True   True  False  False
z3   True  False   True   True
z4  False  False   True  False
z5   True  False  False  False

Es entsteht ein neuer DataFrame mit boolschen Werte, der die gleiche Dimension des ursprünglichen DataFrame besitzt.
Dieser kann jetzt als "Maskierung" eingesetzt werden, um Element aus einem DataFrame zu selektieren.

In [129]:
mask = df>0
df[mask]

           A         B         C         D
z1  0.276266       NaN  0.623901  1.145311
z2  1.037190  1.886639       NaN       NaN
z3  0.148675       NaN  2.171257  1.152310
z4       NaN       NaN  0.539840       NaN
z5  1.314877       NaN       NaN       NaN

Durch `df[mask]` entsteht ein neuer DataFrame, wo nur die durch die Maske `df>0` ausgewählten Elemente enthalten sind.
Die negativen Werte fehlen hier und werden durch 'NaN' dargestellt.

Das geht auch in einer Zeile:

In [130]:
df[df>0]

           A         B         C         D
z1  0.276266       NaN  0.623901  1.145311
z2  1.037190  1.886639       NaN       NaN
z3  0.148675       NaN  2.171257  1.152310
z4       NaN       NaN  0.539840       NaN
z5  1.314877       NaN       NaN       NaN

Schreiben von Werte mit Maske

In [131]:
mask = df<0
df[mask] = 0

In [132]:
df

           A         B         C         D
z1  0.276266  0.000000  0.623901  1.145311
z2  1.037190  1.886639  0.000000  0.000000
z3  0.148675  0.000000  2.171257  1.152310
z4  0.000000  0.000000  0.539840  0.000000
z5  1.314877  0.000000  0.000000  0.000000

----
### Zählen von gültigen Einträgen  mit der `.count()`-Methode

**Aufgabe:** Bestimme die Anzahl der Elemente in jeder Spalte

Die [`.count()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.count.html))-Methode zählt die verfügbaren Elemente (nicht NaN) in Spalten und Zeilen.

- `.count(axis=0)` zählt über die Zeilen und bestimmt die Anzahl der verfügbaren Elemente in einer Spalte  (default Einstellung)
- `.count(axis=1)` zählt über die Spalten und bestimmt die Anzahl der verfügbaren Elemente in einer Zeile

In [133]:
df

           A         B         C         D
z1  0.276266  0.000000  0.623901  1.145311
z2  1.037190  1.886639  0.000000  0.000000
z3  0.148675  0.000000  2.171257  1.152310
z4  0.000000  0.000000  0.539840  0.000000
z5  1.314877  0.000000  0.000000  0.000000

Aufgabe: Bestimme die Anzahl der positiven Einträge

In [134]:
df[df>0]

           A         B         C         D
z1  0.276266       NaN  0.623901  1.145311
z2  1.037190  1.886639       NaN       NaN
z3  0.148675       NaN  2.171257  1.152310
z4       NaN       NaN  0.539840       NaN
z5  1.314877       NaN       NaN       NaN

In [135]:
df[df>0].count()

A    4
B    1
C    3
D    2
dtype: int64

In [136]:
df[df>0].count(axis=1)

z1    3
z2    2
z3    3
z4    1
z5    1
dtype: int64

### Spalten oder zeilenweises Aufsummieren mit der `.sum()`-Methode 

**Aufgabe:** Bestimmen der Gesamtzahl der positiven Zahlen 

Aufsummieren der Elemente mit der [`.sum()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html)-Methode.

In [137]:
df[df>0].count()

A    4
B    1
C    3
D    2
dtype: int64

In [138]:
df[df>0].count().sum()

np.int64(10)

In [139]:
df[df>0].count(axis=1).sum()

np.int64(10)

In [140]:
df

           A         B         C         D
z1  0.276266  0.000000  0.623901  1.145311
z2  1.037190  1.886639  0.000000  0.000000
z3  0.148675  0.000000  2.171257  1.152310
z4  0.000000  0.000000  0.539840  0.000000
z5  1.314877  0.000000  0.000000  0.000000

In [141]:
df[df>0]

           A         B         C         D
z1  0.276266       NaN  0.623901  1.145311
z2  1.037190  1.886639       NaN       NaN
z3  0.148675       NaN  2.171257  1.152310
z4       NaN       NaN  0.539840       NaN
z5  1.314877       NaN       NaN       NaN

In [142]:
df[df>0].count()

A    4
B    1
C    3
D    2
dtype: int64

In [143]:
df[df>0].count().sum()

np.int64(10)

Summe der Elemente in einer Spalte

In [ ]:
df

In [ ]:
df.sum()

Summe der Elemente in einer Zeile

In [ ]:
df.sum(axis=1)

----
### Herausfiltern von bestimmten Zeilen

Wir erzeugen uns eine Maske aus den positiven Zahlen in der Spalte 'B'

Zunächst zur Erinnerung der DataFrame `df` nochmal:

In [151]:
np.random.seed(7) # wir definieren den Startwert des Zufallsgenerators, um immer die gleichen Zufallszahlen zu bekommen
my_columns = ['A', 'B', 'C', 'D']
my_index = ['z1', 'z2', 'z3', 'z4', 'z5']
my_data = np.random.randn(len(my_index),len(my_columns))

df = pd.DataFrame(my_data,my_index,my_columns)
df

           A         B         C         D
z1  1.690526 -0.465937  0.032820  0.407516
z2 -0.788923  0.002066 -0.000890 -1.754724
z3  1.017658  0.600499 -0.625429 -0.171548
z4  0.505299 -0.261356 -0.242749 -1.453241
z5  0.554580  0.123881  0.274460 -1.526525

Bedingung auf Spalte 'B' anwenden:

In [152]:
df['B']>0

z1    False
z2     True
z3     True
z4    False
z5     True
Name: B, dtype: bool

Es entsteht ein Series-Objekt, das wir als Maske auf den ursprünglichen DataFrame anwenden können:

In [153]:
mask = df['B']>0
print(mask)
df[mask]

z1    False
z2     True
z3     True
z4    False
z5     True
Name: B, dtype: bool

           A         B         C         D
z2 -0.788923  0.002066 -0.000890 -1.754724
z3  1.017658  0.600499 -0.625429 -0.171548
z5  0.554580  0.123881  0.274460 -1.526525

Es wird ein neuer DataFrame zurückgegeben, der nur die Zeilen enthält, die in der Maske `df['B']>0` mit True markiert wurden.

Als zusätzlich Anforderung möchte ich nur die Spalten 'C' und 'D' angezeigt bekommen:

In [154]:
mask = df['B']>0
df_auswahl = df[mask]
mein_Spalten = ['C', 'D']
df_auswahl[mein_Spalten]

           C         D
z2 -0.000890 -1.754724
z3 -0.625429 -0.171548
z5  0.274460 -1.526525

Das geht auch in einer Zeile "one-liner":
`df[Bedingung][Auswahl der Spalten]`

In [155]:
df[df['B']>0][['C', 'D']]

           C         D
z2 -0.000890 -1.754724
z3 -0.625429 -0.171548
z5  0.274460 -1.526525

Wir können auch die `.loc[]`-Methode einsetzen: 
`df[Bedingung].loc[Auswahl der Zeilen, Auswahl der Spalten]`

Beispiel: 
- Zeige die Zahlen in den Spalten 'C' und 'D' für die Zeilen deren Werte in Spalte 'B' positiv sind. 
- Zeige aber nur die Zeilen 'z3' bis 'z4' an.

In [156]:
df[df['B']>0].loc['z3':'z4',['C', 'D']]

           C         D
z3 -0.625429 -0.171548

```text
FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.
```

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [157]:
#mask = df['C']>0
#df['C'][mask]=2

mask = df['C']>0
df.loc[mask, 'C'] = 2

In [158]:
df

           A         B         C         D
z1  1.690526 -0.465937  2.000000  0.407516
z2 -0.788923  0.002066 -0.000890 -1.754724
z3  1.017658  0.600499 -0.625429 -0.171548
z4  0.505299 -0.261356 -0.242749 -1.453241
z5  0.554580  0.123881  2.000000 -1.526525

-----
### Komplexere Auswahl-Bedingungen zusammenbauen

Bitweise Boolschen Operatoren:
- `&` logisches Und
- `|` logisches Oder
- `~` Negation

Um Vergleiche immer Klammern setzen !!!

Die logischen Operatoren `and`, `or` und `not` funktionieren hier nicht.

In [159]:
np.random.seed(7) # wir definieren den Startwert des Zufallsgenerators, um immer die gleichen Zufallszahlen zu bekommen
my_columns = ['A', 'B', 'C', 'D']
my_index = ['z1', 'z2', 'z3', 'z4', 'z5']
my_data = np.random.randn(len(my_index),len(my_columns))

df = pd.DataFrame(my_data,my_index,my_columns)
df

           A         B         C         D
z1  1.690526 -0.465937  0.032820  0.407516
z2 -0.788923  0.002066 -0.000890 -1.754724
z3  1.017658  0.600499 -0.625429 -0.171548
z4  0.505299 -0.261356 -0.242749 -1.453241
z5  0.554580  0.123881  0.274460 -1.526525

Beispiel: Zahlen in Spalte 'B' größer als Null und Zahlen in Spalte 'C' kleiner als -0.1

In [160]:
df['B']>0

z1    False
z2     True
z3     True
z4    False
z5     True
Name: B, dtype: bool

In [161]:
df['C']<-0.1

z1    False
z2    False
z3     True
z4     True
z5    False
Name: C, dtype: bool

Bitte auf Klammerung achten, sonst kommt ein Fehler

```Python
df['B']>0 & df['C']<-0.1
```
```
TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]
```

In [162]:
(df['B']>0) & (df['C']<-0.1)

z1    False
z2    False
z3     True
z4    False
z5    False
dtype: bool

In [163]:
mask = (df['B']>0) & (df['C']<-0.1)
df[mask]

           A         B         C         D
z3  1.017658  0.600499 -0.625429 -0.171548

Anwendung des [De-morganschen Gesetzes](https://de.wikipedia.org/wiki/De-morgansche_Gesetze).

In [164]:
~((df['B']<=0) | (df['C']>=-0.1))

z1    False
z2    False
z3     True
z4    False
z5    False
dtype: bool

In [165]:
mask = ~((df['B']<=0) | (df['C']>=-0.1))
df[mask]

           A         B         C         D
z3  1.017658  0.600499 -0.625429 -0.171548

----
### DataFrame kopieren mit `.copy()`-Methode

Eine Zuweisung zu einer neuen Variablen liefert nur eine Referenz auf den ursprünglichen Datensatz:

In [166]:
df2 = df

print(f"id(df) : {id(df)}")
print(f"id(df2): {id(df2)}")

id(df) : 1896176816000
id(df2): 1896176816000

Die Identifikationsnummer der Objekte `df` und `df2` sind identisch, d.h. `df` und `df2` verweisen nur auf das selbe Objekt im Speicher !!!

Mit der `.copy()`-Methode wird ein Dataframe als Kopie des ursprünglichen angelegt.

In [167]:
df_copy = df.copy()
print(f"id(df)     : {id(df)}")
print(f"id(df_copy): {id(df_copy)}")
df_copy

id(df)     : 1896176816000
id(df_copy): 1896185450896

           A         B         C         D
z1  1.690526 -0.465937  0.032820  0.407516
z2 -0.788923  0.002066 -0.000890 -1.754724
z3  1.017658  0.600499 -0.625429 -0.171548
z4  0.505299 -0.261356 -0.242749 -1.453241
z5  0.554580  0.123881  0.274460 -1.526525

Jetzt sind die Identifikationsnummern der Objekte unterschiedlich, d.h. `df` und `df2` verweisen auf unterschiedliche Objekte im Speicher.

---
### Austausch des Index

Mit der [`.reset_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html)-Methode wird der aktuelle Index in die Spalte 'index' übertragen und ein neuer numerischer Index erzeugt.

Zur Erinnerung wieder der DataFrame `df`.
Wir holen uns eine frische Kopie:

In [181]:
df = df_copy.copy()
df

           A         B         C         D
z1  1.690526 -0.465937  0.032820  0.407516
z2 -0.788923  0.002066 -0.000890 -1.754724
z3  1.017658  0.600499 -0.625429 -0.171548
z4  0.505299 -0.261356 -0.242749 -1.453241
z5  0.554580  0.123881  0.274460 -1.526525

Mit dem Parameter `inplace=True` wird Bearbeitung auch auf den aktuellen DataFrame angewendet und nicht nur eine bearbeitete Kopie zurückgegeben:

In [182]:
df.reset_index(inplace=True)
df

  index         A         B         C         D
0    z1  1.690526 -0.465937  0.032820  0.407516
1    z2 -0.788923  0.002066 -0.000890 -1.754724
2    z3  1.017658  0.600499 -0.625429 -0.171548
3    z4  0.505299 -0.261356 -0.242749 -1.453241
4    z5  0.554580  0.123881  0.274460 -1.526525

Anlegen einer Spalte, die neuer Index werden soll:

In [183]:
df['neuer_index'] = ['z1_neu','z2_neu','z3_neu','z4_neu','z5_neu']
df

  index         A         B         C         D neuer_index
0    z1  1.690526 -0.465937  0.032820  0.407516      z1_neu
1    z2 -0.788923  0.002066 -0.000890 -1.754724      z2_neu
2    z3  1.017658  0.600499 -0.625429 -0.171548      z3_neu
3    z4  0.505299 -0.261356 -0.242749 -1.453241      z4_neu
4    z5  0.554580  0.123881  0.274460 -1.526525      z5_neu

Den neuen Index mit der [`.set_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)-Methode setzen:

In [184]:
df.set_index('neuer_index',inplace=True)
df

            index         A         B         C         D
neuer_index
z1_neu         z1  1.690526 -0.465937  0.032820  0.407516
z2_neu         z2 -0.788923  0.002066 -0.000890 -1.754724
z3_neu         z3  1.017658  0.600499 -0.625429 -0.171548
z4_neu         z4  0.505299 -0.261356 -0.242749 -1.453241
z5_neu         z5  0.554580  0.123881  0.274460 -1.526525

Spalte mit dem alten Index aus dem DataFrame entfernen:

In [185]:
df.drop('index',axis=1,inplace=True)
df

                    A         B         C         D
neuer_index
z1_neu       1.690526 -0.465937  0.032820  0.407516
z2_neu      -0.788923  0.002066 -0.000890 -1.754724
z3_neu       1.017658  0.600499 -0.625429 -0.171548
z4_neu       0.505299 -0.261356 -0.242749 -1.453241
z5_neu       0.554580  0.123881  0.274460 -1.526525

alles nochmal untereinander:

In [186]:
df = df_copy.copy()
df.reset_index(inplace=True)
df['neuer_index'] = ['z1_neu','z2_neu','z3_neu','z4_neu','z5_neu']
df.set_index('neuer_index',inplace=True)
df.drop('index',axis=1,inplace=True)
df

                    A         B         C         D
neuer_index
z1_neu       1.690526 -0.465937  0.032820  0.407516
z2_neu      -0.788923  0.002066 -0.000890 -1.754724
z3_neu       1.017658  0.600499 -0.625429 -0.171548
z4_neu       0.505299 -0.261356 -0.242749 -1.453241
z5_neu       0.554580  0.123881  0.274460 -1.526525

---
### Umgang mit fehlenden Daten ('Missing data')

Wir erzeugen uns einen neuen DataFrame, der fehlende Daten enthält:

- Kodierung mit `np.nan`

    Die fehlenden Daten werden einmal durch `np.nan` beschrieben.
    Pandas erkennt dies und gibt diese bei der Ausgabe des DataFrames als `Nan` Not a number dargestellt.
- benutzer definierte NA-Werte (Not Available)
    
    Im anderen Fall werden fehlende Daten durch einen expliziten Text _'nicht vorhanden'_ beschrieben. 
    Pandas kann dies nicht automatisch erkennen und behandelt diese Angabe als normale Zeichenkette.

In [187]:
my_data = {'Name':  ['Anton',          'Bernd', 'Claudia',       'Doris',  'Emil'],
           'Email': ['Anton@gmail.com', np.nan, 'Claudia@gmx.de', np.nan,  'Emil@web.de'],
           'Phone': ['123',            '456',   np.nan,           np.nan,  'nicht vorhanden']}
df = pd.DataFrame(my_data)
df

      Name            Email            Phone
0    Anton  Anton@gmail.com              123
1    Bernd              NaN              456
2  Claudia   Claudia@gmx.de              NaN
3    Doris              NaN              NaN
4     Emil      Emil@web.de  nicht vorhanden

#### Identifikation der Stellen mit fehlenden Daten `.isna()`

Mit der [`.isna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html)-Methode
werden Stellen von fehlenden Daten, die mit `NaN` markiert worden sind durch ein DataFrame mit boolschen Werten dargestellt.

In [188]:
df.isna()

    Name  Email  Phone
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True   True
4  False  False  False

#### Auffüllen der fehlenden Daten mit Werten `.fillna()`

Mit der [`.fillna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html)-Methode wird an die Positionen, wo Daten fehlen, der Übergabewert (im unten stehenden Beispiel: Nullen) geschrieben.

Das ist aber bei der Spalte 'Email' und 'Phone' nicht besonders sinnvoll.

In [189]:
df.fillna(0)

      Name            Email            Phone
0    Anton  Anton@gmail.com              123
1    Bernd                0              456
2  Claudia   Claudia@gmx.de                0
3    Doris                0                0
4     Emil      Emil@web.de  nicht vorhanden

#### Entfernen der Zeilen mit fehlenden Daten `dropna()`

Mit der [`dropna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)-Methode werden Zeile, die irgendwo fehlende Daten enthalten, entfernt.

Hinweis: Wenn man mehr als ausreichend viele Zeilen hat, kann dies ein gangbarer Weg sein, um seinen Datensatz "sauber" für die weitergehende Verarbeitung zu bekommen.

In [190]:
df.dropna()

    Name            Email            Phone
0  Anton  Anton@gmail.com              123
4   Emil      Emil@web.de  nicht vorhanden

#### Ersetzen benutzer definierter NA-Werte `replace()`

Mit der [`.replace('find',np.nan,inplace=True)`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.replace.html)-Methode lassen sind spezifische Zeichenkette durch `np.nan` ersetzen:

In [191]:
df.replace('nicht vorhanden',np.nan)

      Name            Email Phone
0    Anton  Anton@gmail.com   123
1    Bernd              NaN   456
2  Claudia   Claudia@gmx.de   NaN
3    Doris              NaN   NaN
4     Emil      Emil@web.de   NaN

---
## Beschreibende Statistik

Konsolidierung oder Verdichtung von Daten ([Aggregation-Wikipedia](https://de.wikipedia.org/wiki/Aggregation_(OLAP)))

Durch das Bilden von Mittel-, Median-, Minimal-, Maximalwerten usw. kann ein Datensatz auf wenige aussagekräftige Kennwerte (Statistiken) beschrieben werden.

Beispiel für solche Kennwerte sind:

- Anzahl der auswertbaren Daten [`.count()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.count.html)
- Mittelwert, Durchschnitt [`.mean()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html) Wikipedia: [Arithmetisches_Mittel](https://de.wikipedia.org/wiki/Arithmetisches_Mittel)
- Standardabweichung [`.std()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.std.html) Wikipedia [Varianz](https://de.wikipedia.org/wiki/Varianz_(Stochastik))
- Minimum [`.min()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.min.html)
- Maximum [`.max()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.max.html)  
- Median, Zentralwert [`.median()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.median.html)  Wikipedia: [Median](https://de.wikipedia.org/wiki/Median)
- Quantil [`.quantile()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.quantile.html) Wikipedia: [Quantil](https://de.wikipedia.org/wiki/Quantil_(Wahrscheinlichkeitstheorie))

_Bemerkung zu Mittel- und Medianwerten_:
Der Medianwert einer Datenreihe ist deutlich robuster gegenüber Ausreissern, d.h. großen Zahlen, die nicht zu der eigentlichen Verteilung der Zahlen passen.

Wir definieren uns einen neuen DataFrame mit Zufallszahlen:

In [192]:
np.random.seed(7) # wir definieren den Startwert des Zufallsgenerators, um immer die gleichen Zufallszahlen zu bekommen
my_columns = ['A', 'B', 'C', 'D']
my_index = [f'z{k}' for k in range(100)]
my_data = np.random.randn(len(my_index),len(my_columns))

df = pd.DataFrame(my_data,my_index,my_columns)
df

            A         B         C         D
z0   1.690526 -0.465937  0.032820  0.407516
z1  -0.788923  0.002066 -0.000890 -1.754724
z2   1.017658  0.600499 -0.625429 -0.171548
z3   0.505299 -0.261356 -0.242749 -1.453241
z4   0.554580  0.123881  0.274460 -1.526525
..        ...       ...       ...       ...
z95  0.926302 -0.049002 -0.308604 -0.947348
z96 -3.082505 -1.518000 -0.069594 -0.175262
z97  0.403560 -0.126687  0.159358  0.787799
z98 -0.885045 -0.287158 -1.607213  0.972893
z99  0.038418  0.489822  1.542483  1.079546

[100 rows x 4 columns]

Wir berechnen Median und arithmetischen Mittelwert der Spalte 'A':

In [193]:
df['A'].median()

np.float64(0.005001275967058689)

In [194]:
df['A'].mean()

np.float64(0.04730742041475778)

In [195]:
df['A'].min(), df['A'].max()

(np.float64(-3.082504765717661), np.float64(2.8610671907227583))

In [196]:
df['A'].std()

np.float64(1.045948710194599)

Sowohl der Median als auch der arithmetische Mittelwert sind wie erwartet Nahe Null.

Wir bauen in den DataFrame einen Ausreißer in der Spalte 'A' mit dem Wert -10000 ein:

In [197]:
df.loc['z1','A'] = -10000
df.head(7)

               A         B         C         D
z0      1.690526 -0.465937  0.032820  0.407516
z1 -10000.000000  0.002066 -0.000890 -1.754724
z2      1.017658  0.600499 -0.625429 -0.171548
z3      0.505299 -0.261356 -0.242749 -1.453241
z4      0.554580  0.123881  0.274460 -1.526525
z5      1.650700  0.154336 -0.387140  2.029072
z6     -0.045386 -1.450679 -0.405228 -2.288315

In [198]:
df.tail()

            A         B         C         D
z95  0.926302 -0.049002 -0.308604 -0.947348
z96 -3.082505 -1.518000 -0.069594 -0.175262
z97  0.403560 -0.126687  0.159358  0.787799
z98 -0.885045 -0.287158 -1.607213  0.972893
z99  0.038418  0.489822  1.542483  1.079546

Wir berechnen wieder Median und arithmetischen Mittelwert der Spalte 'A':

In [199]:
df['A'].median()

np.float64(0.005001275967058689)

In [200]:
df['A'].mean()

np.float64(-99.944803349299)

Der Mittelwert `.mean()` wird durch eine Ausreisser  `df.loc['z1','A'] = -10000` viel stärker beeinflußt als der Medianwert `.median()`.

Die `.quantile()`-Methode liefert in der Defaulteinstellung mit 50% den Medianwert:

In [201]:
df['A'].quantile()

np.float64(0.0050012759670586895)

Medianwerte für die einzelnen Spalten des DataFrames:

In [202]:
df.median()

A    0.005001
B   -0.064927
C   -0.113260
D    0.101565
dtype: float64

In [203]:
df.median(axis=1)

z0     0.220168
z1    -0.877807
z2     0.214475
z3    -0.252053
z4     0.199170
         ...
z95   -0.178803
z96   -0.846631
z97    0.281459
z98   -0.586101
z99    0.784684
Length: 100, dtype: float64

### Überblick über die Statistiken der einzelnen Spalten eines DataFrames `.describe()` 

In der Defaulteinstellung berechnet die [`.describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)-Methode die Statistiken der einzelnen Spalten eines DataFrames, die numerische Werten enthalten.

Mit dem Parameter `include='all'` werden auch nicht numerische Spalten wie Zeichenketten oder Kategorien ausgewertet

Wir bauen eine fehlenden Wert bei 'z2' und 'A' ein:

In [204]:
df.loc['z2','A'] = np.nan
df

                A         B         C         D
z0       1.690526 -0.465937  0.032820  0.407516
z1  -10000.000000  0.002066 -0.000890 -1.754724
z2            NaN  0.600499 -0.625429 -0.171548
z3       0.505299 -0.261356 -0.242749 -1.453241
z4       0.554580  0.123881  0.274460 -1.526525
..            ...       ...       ...       ...
z95      0.926302 -0.049002 -0.308604 -0.947348
z96     -3.082505 -1.518000 -0.069594 -0.175262
z97      0.403560 -0.126687  0.159358  0.787799
z98     -0.885045 -0.287158 -1.607213  0.972893
z99      0.038418  0.489822  1.542483  1.079546

[100 rows x 4 columns]

In [205]:
df.shape

(100, 4)

In [206]:
df.info()

<class 'pandas.DataFrame'>
Index: 100 entries, z0 to z99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       99 non-null     float64
 1   B       100 non-null    float64
 2   C       100 non-null    float64
 3   D       100 non-null    float64
dtypes: float64(4)
memory usage: 8.0+ KB

In [207]:
df.describe()

                  A           B           C           D
count     99.000000  100.000000  100.000000  100.000000
mean    -100.964626   -0.147641   -0.119835    0.019954
std     1005.042974    0.925316    0.967700    1.009611
min   -10000.000000   -2.291420   -2.305183   -2.288315
25%       -0.578105   -0.749157   -0.658941   -0.681693
50%       -0.012242   -0.064927   -0.113260    0.101565
75%        0.748519    0.562054    0.416827    0.741360
max        2.861067    1.779026    2.638539    2.247595

#### Beispiel: Spalte mit nicht numerischen Werten statitisch auswerten

Wir erzeugen uns eine nicht numerische Spalten nach folgenden Regeln:

| Bedingung | Ausgabe|
| --- | --- |
| -0.25 < x < 0.25 | 'um die Null'|
|   0.25<=x        | 'pos. gross' |
|   x<=-0.25       | 'neg. gross' |

Wir definieren eine Funktion `my_category_fkt(x)`, die die oben beschriebene Logik berechnet:

In [208]:
def my_category_fkt(x):
    if 0.25 <= x:
        return 'pos. gross'
    elif x<=-0.25:
        return 'neg. gross'
    else:
        return 'um die Null'

kurzer Test der Funktion

In [209]:
my_category_fkt(0), my_category_fkt(0.7), my_category_fkt(-0.7)

('um die Null', 'pos. gross', 'neg. gross')

Mit der [`.apply()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html)-Methode kann ich eine Funktion mit einen Paramter und einem Rückgabewert auf die einzelnen Elemente einer Spalte anwenden.

Wir erzeugen uns die neue Spalte 'E':

In [210]:
df['E'] = df['A'].apply(my_category_fkt)
df

                A         B         C         D            E
z0       1.690526 -0.465937  0.032820  0.407516   pos. gross
z1  -10000.000000  0.002066 -0.000890 -1.754724   neg. gross
z2            NaN  0.600499 -0.625429 -0.171548  um die Null
z3       0.505299 -0.261356 -0.242749 -1.453241   pos. gross
z4       0.554580  0.123881  0.274460 -1.526525   pos. gross
..            ...       ...       ...       ...          ...
z95      0.926302 -0.049002 -0.308604 -0.947348   pos. gross
z96     -3.082505 -1.518000 -0.069594 -0.175262   neg. gross
z97      0.403560 -0.126687  0.159358  0.787799   pos. gross
z98     -0.885045 -0.287158 -1.607213  0.972893   neg. gross
z99      0.038418  0.489822  1.542483  1.079546  um die Null

[100 rows x 5 columns]

In [211]:
df.info()

<class 'pandas.DataFrame'>
Index: 100 entries, z0 to z99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       99 non-null     float64
 1   B       100 non-null    float64
 2   C       100 non-null    float64
 3   D       100 non-null    float64
 4   E       100 non-null    str
dtypes: float64(4), str(1)
memory usage: 8.8+ KB

In [212]:
df.describe(include='all')

                   A           B           C           D           E
count      99.000000  100.000000  100.000000  100.000000         100
unique           NaN         NaN         NaN         NaN           3
top              NaN         NaN         NaN         NaN  pos. gross
freq             NaN         NaN         NaN         NaN          41
mean     -100.964626   -0.147641   -0.119835    0.019954         NaN
std      1005.042974    0.925316    0.967700    1.009611         NaN
min    -10000.000000   -2.291420   -2.305183   -2.288315         NaN
25%        -0.578105   -0.749157   -0.658941   -0.681693         NaN
50%        -0.012242   -0.064927   -0.113260    0.101565         NaN
75%         0.748519    0.562054    0.416827    0.741360         NaN
max         2.861067    1.779026    2.638539    2.247595         NaN

Es gibt 3 neue Zeilen:
- _**unique**_ - Anzahl der verschiedenen vorkommenden Werte
- _**top**_ - am häufigsten vorkommender Wert
- _**freq**_ - Anzahl des am häufigsten vorkommenden Wertes

#### Anzahl der verschiedenen vorkommenden Werte `.nunique()`

[`.nunique()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html)-Methode

In [213]:
df['E'].nunique()

3

#### Array mit den verschiedene Werten zurückgeben `.unique()`

[`.unique()`](https://pandas.pydata.org/docs/reference/api/pandas.unique.html)-Methode

In [214]:
df['E'].unique()

<StringArray>
['pos. gross', 'neg. gross', 'um die Null']
Length: 3, dtype: str

#### Häufigkeit der Werte zählen `.value_counts()`

Werte zählen [`.value_counts()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html)

In [215]:
df['E'].value_counts()

E
pos. gross     41
neg. gross     39
um die Null    20
Name: count, dtype: int64

In [216]:
df['A'].value_counts()

A
 1.690526        1
-10000.000000    1
 0.505299        1
 0.554580        1
 1.650700        1
                ..
 0.926302        1
-3.082505        1
 0.403560        1
-0.885045        1
 0.038418        1
Name: count, Length: 99, dtype: int64

Bestimmung von **top** und **freq**:

In [217]:
value_counts = df['E'].value_counts()
value_counts

E
pos. gross     41
neg. gross     39
um die Null    20
Name: count, dtype: int64

In [218]:
value_counts.index[0]

'pos. gross'

In [219]:
value_counts.iloc[0]

np.int64(41)

In [220]:
value_counts = df['E'].value_counts()
top = value_counts.index[0]
freq = value_counts.iloc[0]
top, freq

('pos. gross', np.int64(41))

------
### Groupby - Gruppieren und Zusammenfassen

[`.groupby()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)

Siehe auch Folien in der ppt-Präsentation.

Zunächst kleines Beispiel: Ein DatenFrame mit einer Spalte 'Gruppe' und einer Spalte 'Wert'

In [221]:
data = {'Gruppe': ['A','A','A','B','B','C','C','C'],
        'Wert'  : [  1,  2,  3, 10, 20,  9,  8,  7]}
df2 = pd.DataFrame(data=data)
df2

  Gruppe  Wert
0      A     1
1      A     2
2      A     3
3      B    10
4      B    20
5      C     9
6      C     8
7      C     7

Aufgabe: Summieren Sie die Werte jeweils einer Gruppe

In [222]:
df2.groupby(['Gruppe'])

mit der [`.get_group()`](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.GroupBy.get_group.html)-Methode erste Gruppe herausholen:

```Python
df2.groupby(['Gruppe']).get_group('A')
```

```text
FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df2.groupby(['Gruppe']).get_group('A')
```

In [223]:
df2.groupby('Gruppe',).get_group('A')

  Gruppe  Wert
0      A     1
1      A     2
2      A     3

Spalte 'Wert'

In [228]:
df2.groupby('Gruppe').get_group('A')['Wert']

0    1
1    2
2    3
Name: Wert, dtype: int64

Berechnen der Summe der ersten Gruppe

In [229]:
df2.groupby('Gruppe').get_group('A')['Wert'].sum()

np.int64(6)

jetzt für alle Gruppen die Summen berechnen

In [227]:
df2.groupby('Gruppe')['Wert'].sum()

Gruppe
A     6
B    30
C    24
Name: Wert, dtype: int64

Jetzt die Anzahl der Werte in den Gruppen bestimmen:

In [230]:
df2.groupby('Gruppe',)['Wert'].count()

Gruppe
A    3
B    2
C    3
Name: Wert, dtype: int64

Mit der [`.agg()`](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.GroupBy.agg.html)-Methode lassen sich mehrer Aggregationen wie `sum` und `count` mit einem Befehl ausführen:

In [232]:
df2.groupby('Gruppe')['Wert'].agg(['sum','count'])

        sum  count
Gruppe
A         6      3
B        30      2
C        24      3

#### Jetzt geht es mit dem großen DataFrame von oben weiter:

In [233]:
df

                A         B         C         D            E
z0       1.690526 -0.465937  0.032820  0.407516   pos. gross
z1  -10000.000000  0.002066 -0.000890 -1.754724   neg. gross
z2            NaN  0.600499 -0.625429 -0.171548  um die Null
z3       0.505299 -0.261356 -0.242749 -1.453241   pos. gross
z4       0.554580  0.123881  0.274460 -1.526525   pos. gross
..            ...       ...       ...       ...          ...
z95      0.926302 -0.049002 -0.308604 -0.947348   pos. gross
z96     -3.082505 -1.518000 -0.069594 -0.175262   neg. gross
z97      0.403560 -0.126687  0.159358  0.787799   pos. gross
z98     -0.885045 -0.287158 -1.607213  0.972893   neg. gross
z99      0.038418  0.489822  1.542483  1.079546  um die Null

[100 rows x 5 columns]

In [234]:
df_group = df.groupby(['E'])
df_group

In [235]:
df_group.get_group(('um die Null',))['A']

z2          NaN
z6    -0.045386
z13    0.101434
z18    0.108648
z21   -0.196027
z23   -0.012242
z29    0.022245
z31   -0.075814
z34    0.088155
z38   -0.193856
z43   -0.090981
z46    0.116560
z55    0.178290
z57   -0.049672
z60   -0.132788
z62   -0.107667
z63   -0.185361
z88   -0.203527
z93    0.121999
z99    0.038418
Name: A, dtype: float64

In [236]:
df_group.get_group(('um die Null',))['A'].count()

np.int64(19)

In [237]:
df_group.get_group(('um die Null',))['A'].median()

np.float64(-0.04538602986064609)

In [238]:
df.groupby(['E'])['A'].median()

E
neg. gross    -0.864490
pos. gross     0.932750
um die Null   -0.045386
Name: A, dtype: float64

In [239]:
df.groupby(['E']).median()

                    A         B         C         D
E
neg. gross  -0.864490  0.002066 -0.012994 -0.222950
pos. gross   0.932750 -0.126687 -0.287984  0.237302
um die Null -0.045386  0.345541 -0.149663 -0.018253

---
## Datentypen wandeln

[`.astype()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html)

In [240]:
my_index   = ['Zeile1','Zeile2','Zeile3','Zeile4']
my_columns = ['Spalte1','Spalte2','Spalte3']
my_data    = [[ 1, 2, 3],
              [ 4, 5, 6],
              [ 7, 8, 9],
              [10,11,12]]
df = pd.DataFrame(data=my_data,index=my_index,columns=my_columns)
df

        Spalte1  Spalte2  Spalte3
Zeile1        1        2        3
Zeile2        4        5        6
Zeile3        7        8        9
Zeile4       10       11       12

In [241]:
df.dtypes

Spalte1    int64
Spalte2    int64
Spalte3    int64
dtype: object

In [242]:
df.astype(float)

        Spalte1  Spalte2  Spalte3
Zeile1      1.0      2.0      3.0
Zeile2      4.0      5.0      6.0
Zeile3      7.0      8.0      9.0
Zeile4     10.0     11.0     12.0

In [243]:
df[['Spalte1','Spalte2']].astype(float)

        Spalte1  Spalte2
Zeile1      1.0      2.0
Zeile2      4.0      5.0
Zeile3      7.0      8.0
Zeile4     10.0     11.0

In [244]:
df['Spalte1'].astype(float)

Zeile1     1.0
Zeile2     4.0
Zeile3     7.0
Zeile4    10.0
Name: Spalte1, dtype: float64